# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b34731e09e22e95e0180db988fabb6c4ed1c47bc48b2031f9bde62b4d528d913f1121ce8df1d247abf1b99089865e87d35745e814d372dcefccb3b94ff01cfeb

test:
  secret_key_base: 3afe14354791c043e3eb9f254a3d58459f087f748619ba0514354577ffd27eb489cf5d7bb6f5b764798c993b885a3828a359de2c58f984aa588f5270579bbdb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
